name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    env:
      JAVA_DOWNLOAD_CHECKSUM: 2226366d7dffb3eb4ec3d14101f4ddb4259195aa43bb319a93810447b8384930
    steps:
      - uses: actions/checkout@v1
      - run: |
          wget "https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.1%2B9/OpenJDK13U-jdk_x64_linux_hotspot_13.0.1_9.tar.gz"
          echo "${JAVA_DOWNLOAD_CHECKSUM}  OpenJDK13U-jdk_x64_linux_hotspot_13.0.1_9.tar.gz"  | sha256sum -c
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
          jdkFile: ./OpenJDK13U-jdk_x64_linux_hotspot_13.0.1_9.tar.gz
      - name: Build with Maven
        run: ./mvnw verify